---
version: '3'

services:
  feedback-app:
    image: feedback-app
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 80:80
    volumes:
      - ~/ssl:/ssl
  feedback-app-api:
    image: timmo001/feedback-app-api
    environment:
      CERTIFICATES_DIR: /ssl
    ports:
      - 3234:3234
    volumes:
      - ~/ssl:/ssl
