---
version: '3'

services:
  feedback-app:
    image: timmo001/feedback-app
    ports:
      - 3234:3234
      - 8234:8234
    volumes:
      - ~/feedback-app-config.json:/data/config.json
      - ~/ssl/fullchain.pem:/data/ssl/fullchain.pem
      - ~/ssl/privkey.pem:/data/ssl/privkey.pem
